---
version: "3"
services:
    node:
        image: "becodeorg/node"
        environment:
            NODE_ENV: "development"
            APP_PORT: 12345
            SECRET_KEY: "Super banana !"
        volumes:
            - "./package.json:/src/app/package.json"
            - "./node_modules:/src/app/node_modules"
            - "./bin:/src/app/bin"
        expose:
            - "12345"
            - "9229"
        ports:
            - "80:12345"
            - "9229"
        command: "nodemon --inspect=0.0.0.0:9229 --watch bin"
    postgres:
        image: "postgres"
        restart: "unless-stopped"
        ports:
            - "5432:5432"
        volumes:
            - "postgres_db:/var/lib/postgresql/data"
        environment:
            POSTGRES_USER: "dev"
            POSTGRES_PASSWORD: "dev"
volumes:
    postgres_db:
